### ISSUE TITLE
no path error 

### ISSUE THREAD

**Issue by caomulaodao** [Laurian/ffmpeg-remix#1]
run example

`/Users/laodao/www/dao-kuaikan-video/app/script/a.mp4
null
/Users/laodao/www/dao-kuaikan-video/node_modules/ffmpeg-remix/dist/index.js:109
          throw _iteratorError;
          ^

TypeError: Cannot read property 'path' of null
    at /Users/laodao/www/dao-kuaikan-video/node_modules/ffmpeg-remix/dist/index.js:97:27
    at /Users/laodao/www/dao-kuaikan-video/node_modules/ffmpeg-remix/node_modules/async/dist/async.js:486:20
    at /Users/laodao/www/dao-kuaikan-video/node_modules/ffmpeg-remix/node_modules/async/dist/async.js:1074:13
    at /Users/laodao/www/dao-kuaikan-video/node_modules/ffmpeg-remix/node_modules/async/dist/async.js:486:20
    at iterateeCallback (/Users/laodao/www/dao-kuaikan-video/node_modules/ffmpeg-remix/node_modules/async/dist/async.js:865:21)
    at /Users/laodao/www/dao-kuaikan-video/node_modules/ffmpeg-remix/node_modules/async/dist/async.js:847:20
    at /Users/laodao/www/dao-kuaikan-video/node_modules/ffmpeg-remix/node_modules/async/dist/async.js:1071:17
    at FfmpegCommand.<anonymous> (/Users/laodao/www/dao-kuaikan-video/node_modules/ffmpeg-remix/dist/index.js:72:7)
    at emitThree (events.js:97:13)
    at FfmpegCommand.emit (events.js:175:7)`

**Comment by Laurian** [comment]
weird, I will try to reproduce

**Comment by araphp1** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @jaynewey, @AhmedEzzat12, @LinArcX, @ATDaniel, @ivpusic, @unkoshin, @roycordero
